#ifndef BUILIB_COMPONENTS_GLOBAL_H
#define BUILIB_COMPONENTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BUILIB_LIBRARY)
#  define BUILIB_COMP_EXPORT Q_DECL_EXPORT
#else
#  define BUILIB_COMP_EXPORT Q_DECL_IMPORT
#endif

#endif // BUILIB_COMPONENTS_GLOBAL_H
